name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Install Dev Deps (gate)
        run: npm i -D @babel/parser ajv yaml glob minimatch eslint @eslint/js typescript-eslint globals
      - name: Anti-Hallucination Gate
        run: npm run ah:gate
      - name: Patch Baselines (critical files)
        run: node scripts/check_patch_baselines.mjs
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
