name: infra-validate
on:
  pull_request:
    paths: ["infra/**"]
  push:
    paths: ["infra/**"]
jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=infra/terraform/phi-zone fmt -check
      - run: terraform -chdir=infra/terraform/phi-zone init -backend=false
      - run: terraform -chdir=infra/terraform/phi-zone validate
