name: npm-audit
on:
  workflow_dispatch:
  push:
    paths:
      - "apps/web/package.json"
      - "apps/web/package-lock.json"
      - ".github/workflows/npm-audit.yml"

jobs:
  npm-audit:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Clean install
        run: npm ci

      - name: Audit (prod)
        run: npm audit --audit-level=high
