name: Precheck Security & Hygiene
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  precheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks (secrets)
        run: |
          if command -v gitleaks >/dev/null 2>&1; then gitleaks version; fi
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_x64.tar.gz \
            | tar -xz && sudo mv gitleaks /usr/local/bin/
          gitleaks detect --no-git --exit-code 1
      - name: Semgrep (SAST)
        run: |
          pipx install semgrep || pip install --user semgrep
          ~/.local/bin/semgrep --version || semgrep --version || true
          semgrep scan --error --config p/ci --config .semgrep.custom.yml
      - name: Read-only header/route smokes (optional)
        env:
          PROD_URL: https://oneearlybird.ai
          PREVIEW_URL: ${{ vars.PREVIEW_URL }}
        run: |
          if [ -f scripts/smoke_readonly.sh ]; then bash scripts/smoke_readonly.sh; else
            echo "smoke_readonly.sh not present — skipping"; fi
