name: Security Audit (npm)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            apps/web/package-lock.json
            package-lock.json

      - name: Clean install
        run: npm ci

      - name: Audit (prod)
        run: npm audit --audit-level=high

      - name: Audit (dev)
        run: npm audit --audit-level=high --omit=prod
