name: Semgrep CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    # Initially non-blocking; we can flip to false once green
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/ci@v1
        with:
          config: |
            .semgrep/earlybird.yml
            p/owasp-top-ten
            p/javascript
          generateSarif: true
          publishDeployment: false

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

